### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by xinyueliii** [MingTian99/ESDNet#5]
(base) root@autodl-container-99af43bb17-9ca193b3:~/autodl-tmp/ESDNet-master/ESDNet-master# python train.py
[0]
===> Start Epoch 1 End Epoch 1001
===> Loading datasets
  0%|                                                                                                     | 0/150 [00:01<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    restored = model_restoration(input_)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/ESDNet-master/ESDNet-master/model.py", line 178, in forward
    out_enc_level1 = self.encoder_level1(inp_enc_level1) # SRB Spiking Residual Block
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/ESDNet-master/ESDNet-master/model.py", line 77, in forward
    out = self.residual(x) + self.shortcut(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/spikingjelly/activation_based/layer.py", line 1832, in forward
    return functional.seq_to_ann_forward(x_seq, super().forward)
  File "/root/miniconda3/lib/python3.8/site-packages/spikingjelly/activation_based/functional.py", line 686, in seq_to_ann_forward
    y = stateless_module(y)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 135, in forward
    self._check_input_dim(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 80, in _check_input_dim
    raise NotImplementedError
NotImplementedError
您好！我遇到了NotImplementedError这个问题，不知道该怎么解决

**Comment by xinyueliii** [comment]
已经解决了

**Comment by blackseven-white** [comment]
@Sophia-615 请问您是怎么解决的

**Comment by tukumax** [comment]
直接用pip安装的不是最新版，要先git clone，在python setup.py install

**Comment by Feecuin** [comment]
> 直接用pip安装的不是最新版，要先git clone，在python setup.py install

你好，我装了最新的15为啥还是不行呀

**Comment by tukumax** [comment]
> > 直接用pip安装的不是最新版，要先git clone，在python setup.py install
> 
> 你好，我装了最新的15为啥还是不行呀

xrh329409775@163.com

**Comment by blackseven-white** [comment]
我装完15就能跑了 没有报那个NotImplementedError的错误了。
你确定装上了吗？



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MingTian99/ESDNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月22日(星期五) 晚上8:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MingTian99/ESDNet] NotImplementedError (Issue #5)





   
直接用pip安装的不是最新版，要先git clone，在python setup.py install
  
你好，我装了最新的15为啥还是不行呀
  
***@***.***

**Comment by Feecuin** [comment]
> 我装完15就能跑了 没有报那个NotImplementedError的错误了。 你确定装上了吗？ &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MingTian99/ESDNet" ***@***.***&gt;; 发送时间:&nbsp;2024年11月22日(星期五) 晚上8:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MingTian99/ESDNet] NotImplementedError (Issue #5) 直接用pip安装的不是最新版，要先git clone，在python setup.py install 你好，我装了最新的15为啥还是不行呀 ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

确实hh，仔细检查版本装上之后就没问题，但是现在有个新问题，为啥我训出来的模型test的时候说权重对不上？老哥遇过这个问题吗
