### ISSUE TITLE
维度对不上问题

### ISSUE THREAD

**Issue by jiahaoren** [MingTian99/ESDNet#8]
作者您好，遇到了问题。输入到第一个编码器层是5维x: torch.Size([4, 12, 48, 64, 64])   但是ThresholdDependentBatchNorm2d只能输入4d
torch.Size([12, 3, 64, 64])
torch.Size([4, 12, 3, 64, 64])
torch.Size([4, 12, 48, 64, 64])
x: torch.Size([4, 12, 48, 64, 64])
  0%|                                                                                                                                                                         | 0/150 [00:01<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    restored = model_restoration(input_)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/ESDNet-master/model.py", line 182, in forward
    out_enc_level1 = self.encoder_level1(inp_enc_level1)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/ESDNet-master/model.py", line 78, in forward
    out = self.residual(x) + self.shortcut(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/spikingjelly/activation_based/layer.py", line 1832, in forward
    return functional.seq_to_ann_forward(x_seq, super().forward)
  File "/root/miniconda3/lib/python3.8/site-packages/spikingjelly/activation_based/functional.py", line 686, in seq_to_ann_forward
    y = stateless_module(y)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 134, in forward
    self._check_input_dim(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 79, in _check_input_dim
    raise NotImplementedError

**Comment by tanvirnwu** [comment]
Hi, thank you for posting. 
I am also having the same issue. Have you been able to find any solution?

**Comment by xiao143168** [comment]
我在https://github.com/fangwei123456/spikingjelly/blob/master/README_cn.md安装spikingjelly最新版的，并使用环境pytorch-2.2.0-py3.10-cuda11.8-u22.04成功跑起来了，可以试一下
